baseURL = 'https://blog.pieland.xyz/'
languageCode = 'en-us'
title = "pie's personal website"
theme = 'dark-theme-editor'

[markup.goldmark.renderer]
    unsafe= true

[params]
    [params.site]
        localCss = []
        externalCss = []
        localJs = []
        externalJs = []
        faviconUrl = "https://avatars.githubusercontent.com/u/138131197?s=128&v=4"

    [params.header]
        title = "pieland"
        subtitle = " "

    [params.homePage]
        siteLongDescriptionTitle = ""
        siteLongDescription = ""
        recentPostShowUrl = false

    [params.page]
        includeToc = false

    [params.globalFrontmatter]
        author = "pie"
        description = "there would be a description here but I can't think of any"
        keywords = "pie"

    [params.footer]
        copyrightStr = ""
        counter = false
        language = false
        hugoVersion = false
        theme = false
        modifiedTime = false
        dateFormat = ""
        gitHash = false

        [params.footer.socialLink]
            github = "https://github.com/4pii4"
            discord = "https://discordapp.com/users/1018396405498396753"